apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiss-deployment
  labels:
    app: swiss-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiss-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: swiss-deployment
    spec:
      imagePullSecrets:
        - name: dockerhub-credentials
      containers:
        - name: swiss-container
          image: swore:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000