apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-swiss-deployment
  labels:
    app: swiss-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiss-app  # Update the selector if needed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: swiss-app  # Update the labels if needed
    spec:
      imagePullSecrets:
        - name: dockerhub-credentials
      containers:
        - name: swiss-container
          image: shadowhub/beer_factory_app
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi